### ISSUE TITLE
[feature] 优化在歌单中搜索后的听歌体验

### ISSUE THREAD

**Issue by WuJunkai2004** [brandonw3612/LyricEase.PlaybackEngine#5]
目前在歌单中搜索后，点击任何一首歌曲，开始播放后的播放列表依然是整个歌单。
希望可以更改歌单的生成逻辑，使其仅播放搜索列表里面的歌曲。

**Comment by brandonw3612** [comment]
近期暂不接收相关反馈. 在年底前完成 WinUI 3 迁移后将着手进行解决. 届时将提供新反馈入口. 感谢关注.
